version : "3.9"
services: 

  discovery:
    build: ../erukaServer
    ports:
      - "8761:8761"
    image: erueka
  
  candidat:
    build: ../Ms_candidate
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8082:8082"
    image: "ms_candidat"
    depends_on:
      - job_A
  
  job_A:
    build: ../Ms_job
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8083:8083"
    image: "ms_job"

  gateway:
    build: ../gateway_service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8081:8081"
    image: "ms_gateway"
    depends_on:
      - job_A
      - candidat